export const EVENT_TYPES = {
  KICKOFF: "KICKOFF",
  GOAL: "GOAL",
  SHOT: "SHOT",
  SHOT_ON_TARGET: "SHOT_ON_TARGET",
  SAVE: "SAVE",
  CORNER: "CORNER",
  FREE_KICK: "FREE_KICK",
  YELLOW_CARD: "YELLOW_CARD",
  RED_CARD: "RED_CARD",
  SUBSTITUTION: "SUBSTITUTION",
  DANGEROUS_ATTACK: "DANGEROUS_ATTACK",
  OFFSIDE: "OFFSIDE",
  FOUL: "FOUL",
  POSSESSION_CHANGE: "POSSESSION_CHANGE",
  HALF_TIME: "HALF_TIME",
  SECOND_HALF: "SECOND_HALF",
  FULL_TIME: "FULL_TIME"
};

export const TTL_DURATIONS = {
  ROOM: 24 * 60 * 60, // 24 hours
  CONNECTION: 2 * 60 * 60, // 2 hours
};
